"""Text-PDF document registration, extraction, and chunking boundaries."""

from bidded.documents.chunk_embeddings import (
    ChunkEmbeddingAdapter,
    ChunkEmbeddingError,
    DocumentChunkEmbeddingResult,
    populate_document_chunk_embeddings,
)
from bidded.documents.company_kb import (
    CompanyKbDocumentSummary,
    CompanyKbDocumentType,
    CompanyKbError,
    CompanyKbFactExtractor,
    CompanyKbIngestionResult,
    CompanyKbRegistrationResult,
    CompanyKbUploadFile,
    EvidenceExcerptRef,
    ExtractedCompanyKbFact,
    ExtractedCompanyKbFacts,
    RuleBasedCompanyKbFactExtractor,
    build_company_kb_chunks,
    delete_company_kb_document,
    ingest_company_kb_document,
    list_company_kb_documents,
    list_company_kb_evidence,
    register_company_kb_documents,
)
from bidded.documents.pdf_ingestion import (
    ExtractedPdfPage,
    PdfDocumentChunk,
    PdfIngestionError,
    PdfIngestionResult,
    build_document_chunks,
    ensure_tender_evidence_items_for_document,
    ingest_tender_pdf_document,
)
from bidded.documents.tender_registration import (
    TenderPdfRegistrationError,
    TenderPdfRegistrationResult,
    register_demo_tender_pdf,
)

__all__ = [
    "ChunkEmbeddingAdapter",
    "ChunkEmbeddingError",
    "CompanyKbDocumentSummary",
    "CompanyKbDocumentType",
    "CompanyKbError",
    "CompanyKbFactExtractor",
    "CompanyKbIngestionResult",
    "CompanyKbRegistrationResult",
    "CompanyKbUploadFile",
    "DocumentChunkEmbeddingResult",
    "EvidenceExcerptRef",
    "ExtractedCompanyKbFact",
    "ExtractedCompanyKbFacts",
    "ExtractedPdfPage",
    "PdfDocumentChunk",
    "PdfIngestionError",
    "PdfIngestionResult",
    "RuleBasedCompanyKbFactExtractor",
    "TenderPdfRegistrationError",
    "TenderPdfRegistrationResult",
    "build_company_kb_chunks",
    "build_document_chunks",
    "delete_company_kb_document",
    "ensure_tender_evidence_items_for_document",
    "ingest_company_kb_document",
    "ingest_tender_pdf_document",
    "list_company_kb_documents",
    "list_company_kb_evidence",
    "populate_document_chunk_embeddings",
    "register_company_kb_documents",
    "register_demo_tender_pdf",
]
